title: Chungha Sung
description: Chungha's Website

url: http://www.chunghasung.org
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects
 - title: CV
   url: /cv

social:
   github: chunghasung
   linkedin: sch8906

google_analytics: "UA-58263416-1"
